import { Job, duration, money, priceJob, Rates } from '../../services/production/model';
import { NumberField, Panel } from './Fields';
export function EstimateView({ job, onRates }: { job: Job; onRates: (r: Rates) => void }) {
  const result = job.estimate!; let quote; let error=''; try { quote=priceJob(job.quantity,result,job.rates); } catch(e) { error=(e as Error).message; }
  const parts = [{label:'Setup',value:result.breakdown.preparation,color:'#4f46e5'}, {label:'Handling',value:result.breakdown.handling,color:'#60a5fa'}, {label:'Sewing',value:result.breakdown.stitching,color:'#34b58b'}, {label:'Stops',value:result.breakdown.colors+result.breakdown.trims+result.breakdown.reliability,color:'#eab308'}, {label:'Buffer',value:result.breakdown.buffer,color:'#fb923c'}];
  const rate=(key:keyof Rates,n:number)=>onRates({...job.rates,[key]:n});
  return <><h1>Your production plan</h1><Panel className="p-total"><p>Total production time</p><strong className="p-duration">{duration(result.netMinutes)}</strong><div className="p-grid-2 p-time-pair"><div>Machine time<strong>{duration(result.machineMinutes)}</strong></div><div>Operator time<strong>{duration(result.operatorMinutes)}</strong></div></div></Panel>
    <Panel><h2>Machine batch plan</h2>{result.locations.map(l => <div className="p-batch" key={l.id}><p><strong>{l.batches} {l.batches===1?'run':'runs'}</strong> · {l.quantity} items · {Math.min(job.machine.heads,l.quantity)} usable heads{result.locations.length>1 ? ` · ${l.designNumber || 'Design'}` : ''}</p><div className="p-runs" aria-label={`${l.batches} machine runs`}>
      {Array.from({length:Math.min(l.batches,4)},(_,i)=>{const run=i===3&&l.batches>4?l.batches-1:i;const items=Math.min(job.machine.heads,l.quantity-run*job.machine.heads);return <div key={i}><div className="p-dots">{Array.from({length:Math.min(job.machine.heads,12)},(_,n)=><i key={n} className={n<items?'active':''}/>)}{job.machine.heads>12&&<small>+{job.machine.heads-12}</small>}</div><small>Run {run+1}<br/>{items} {items===1?'item':'items'}</small></div>;})}</div></div>)}<p className="p-hint">Each design runs in sequence. Partly filled runs still take a full sewing cycle.</p></Panel>
    <Panel><h2>Where the time goes</h2><div className="p-bar" aria-hidden="true">{parts.map(p=><span key={p.label} style={{background:p.color,width:`${p.value/result.netMinutes*100}%`}}/>)}</div><dl className="p-breakdown">{parts.map(p=><div key={p.label}><dt><i style={{background:p.color}}/>{p.label}</dt><dd>{duration(p.value)}</dd></div>)}</dl><p className="p-hint">Includes {Math.round(job.calibration.contingencyPercent*100)}% contingency. This is a planning estimate; validate new designs with a sew-out.</p></Panel>
    {!!result.warnings.length && <details className="p-details"><summary>Review {result.warnings.length} production notes</summary>{result.warnings.map((w,i)=><p className="p-hint" key={i}>{w}</p>)}</details>}
    <section className="p-costs"><h2>Costs</h2><p className="p-hint">Starter rates are editable. Set them to your shop before sharing a quote.</p><NumberField label="Blank / item" value={job.rates.blank} suffix="$" onChange={n=>rate('blank',n)}/><NumberField label="Labor / hour" value={job.rates.laborHourly} suffix="$" onChange={n=>rate('laborHourly',n)}/><NumberField label="Target margin" value={job.rates.margin} suffix="%" max={94.99} onChange={n=>rate('margin',n)} hint="Margin is profit as a share of the selling price, not markup."/>
    <details className="p-details"><summary>More cost settings</summary><div className="p-grid-2">{([['consumables','Consumables / item'],['machineHourly','Machine / hour'],['overheadHourly','Overhead / hour'],['setupCost','Additional job cost'],['taxPercent','Tax %']] as [keyof Rates,string][]).map(([key,label])=><NumberField key={key} label={label} value={job.rates[key]} max={key==='taxPercent'?100:undefined} onChange={n=>rate(key,n)}/>)}</div><p className="p-hint">Labor uses hands-on minutes. Machine cost uses machine occupancy. Overhead uses elapsed production time. Avoid charging the same overhead in two rates.</p></details></section>
    {error?<p role="alert" className="p-warning">{error}</p>:quote&&<><Panel className="p-quote"><div><span>Quote total</span><strong>{money(quote.total)}</strong></div><span>{money(quote.perItem)} / item</span></Panel><details className="p-details"><summary>Price breakdown</summary><dl className="p-breakdown">{quote.lines.map(l=><div key={l.label}><dt>{l.label}</dt><dd>{money(l.amount)}</dd></div>)}<div><dt>Profit before tax</dt><dd>{money(quote.profit)}</dd></div><div><dt>Tax</dt><dd>{money(quote.tax)}</dd></div></dl></details></>}
  </>;
}
